version: '3'

services:
  db:
    image: postgres
    container_name: payment-file-manager-db
    ports:
      - '5432:5432'
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=payment-file-manager
  redis:
    image: redis
    container_name: payment-file-manager-redis
    ports:
      - '6379:6379'
    command: redis-server --requirepass 'redis'
